version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mynote_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_app
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: mynote_db

volumes:
  db_data:

